import numpy as np
from scipy.interpolate import interp1d
from .settings import LEAKAGE_DATA_DIRECTORY

def load_generic_modf_file(filename):
    energies, modfs = np.load(filename)
    return interp1d(energies, modfs, bounds_error=False, fill_value=0)

def get_mom_modf(energies):
    '''
    Get the modulation factor at certain energies for Moments data

    Parameters
    ----------
    energies: array-like
        Array of energies in keV

    Returns
    -------
    array-like
        Modulation factors from the IXPEobssim load_modf function with ixpe:obssim:v12 calibration, averaged over all three detectors.
    '''
    return load_generic_modf_file(f"{LEAKAGE_DATA_DIRECTORY}/modulation/mom.npy")(energies)

def get_nn_modf(energies):
    '''
    Get the modulation factor at certain energies for NN data

    Parameters
    ----------
    energies: array-like
        Array of energies in keV

    Returns
    -------
    array-like
        Modulation factors measured by Jack Dinsmore from simulations generated by A. Lawrence Peirson in 2022 and analyzed with his neural net

    Notes
    -----
    - Energy dependent modulation factors do not take full advantage of the NN analysis. It is better to use the per-event modulation factors, W_NN, if at all possible. Use the `leakagelib.IXPEData.weight_nn` function to use these weights.
    '''
    return load_generic_modf_file(f"{LEAKAGE_DATA_DIRECTORY}/modulation/nn.npy")(energies)